# Generated by Django 5.1.6 on 2025-03-07 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_productcategory_value_alter_productcategory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategoryattribute',
            name='field_name',
            field=models.CharField(max_length=100, verbose_name='Field Name'),
        ),
        migrations.AlterField(
            model_name='productcategoryattribute',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='price.productcategory', verbose_name='Product Category'),
        ),
    ]
