# Generated by Django 5.1.6 on 2025-03-21 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0003_alter_productcategoryattribute_field_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_for_sale',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(limit_choices_to={'tn_children_pks': ''}, on_delete=django.db.models.deletion.PROTECT, related_name='product_categories', to='price.productcategory', verbose_name='Category'),
        ),
    ]
